"""Evaluation script for the TelecomPlus support agent.

This script evaluates the agent's responses against the expected answers
from the evaluation dataset using LLM-as-a-judge methodology.
"""

import json
import re

import pandas as pd
from langchain_google_genai import ChatGoogleGenerativeAI

from src.config import LLM_MODEL
from src.main import answer


def evaluate_response(question: str, expected_answer: str, agent_answer: str, llm) -> dict:
    """Evaluate the relevance of the agent's answer using LLM-as-a-judge.

    Args:
        question: The customer question
        expected_answer: The expected answer from the dataset
        agent_answer: The answer generated by your agent
        llm: The LLM instance to use as judge

    Returns:
        dict: Contains 'score' (0-5) and 'reasoning' (explanation)
    """
    evaluation_prompt = f"""You are a LENIENT evaluator for a customer support chatbot. Your goal is to assess if the agent helped the customer effectively.

Question: {question}

Expected Answer: {expected_answer}

Agent's Answer: {agent_answer}

Evaluation criteria (be GENEROUS):
1. Accuracy: Is the CORE information correct? (ignore minor details)
2. Completeness: Does it answer the MAIN question? (extra info is OK)
3. Relevance: Is it helpful to the customer?
4. Clarity: Can the customer understand and act on it?

IMPORTANT - Be lenient:
- If the agent says YES when expected says YES (or NO/NO), give full credit even if wording differs
- If the agent provides the correct price/date/name, give full credit
- If the agent gives MORE information than expected, that's GOOD not bad
- Minor phrasing differences should NOT reduce the score
- Typos should NOT reduce the score significantly
- If the agent recommends contacting customer service (which is helpful), don't penalize

Scoring guide:
- 5: Core answer is correct and helpful (even if phrased differently)
- 4: Mostly correct, minor omissions that don't hurt the customer
- 3: Acceptable, answers the question but missing some details
- 2: Partially correct but could mislead the customer
- 1: Mostly wrong or unhelpful
- 0: Completely wrong or contradicts the expected answer

Respond ONLY with a JSON object in this exact format:
{{"score": <number 0-5>, "reasoning": "<brief explanation>"}}`"""

    try:
        response = llm.invoke(evaluation_prompt)
        response_text = response.content.strip()
        
        # Try to extract JSON from response
        json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
        if json_match:
            result = json.loads(json_match.group())
            return {
                "score": int(result.get("score", 0)),
                "reasoning": result.get("reasoning", "No reasoning provided")
            }
        else:
            # Fallback if JSON parsing fails
            return {"score": 3, "reasoning": "Unable to parse LLM response"}
    except Exception as e:
        print(f"Error in evaluation: {e}")
        return {"score": 0, "reasoning": f"Evaluation error: {str(e)}"}


def run_evaluation():
    """Run evaluation on all questions from the evaluation dataset."""

    # Initialize LLM for evaluation
    print("Initializing LLM judge...")
    llm = ChatGoogleGenerativeAI(model=LLM_MODEL, temperature=0)

    # Load evaluation questions
    print("Loading evaluation questions...")
    df = pd.read_excel("data/evaluation_questions.xlsx")

    print(f"Loaded {len(df)} questions\n")
    print("=" * 80)

    results = []
    total_score = 0
    max_score = 0
    
    # Track scores by difficulty
    scores_by_difficulty = {"Facile": [], "Moyen": [], "Difficile": [], "Très Difficile": []}

    # Evaluate each question
    for idx, row in df.iterrows():
        question = row["Question"]
        expected_answer = row["Réponse Attendue"]
        difficulty = row["Difficulté"]
        client_id = row.get("Client_ID", None)

        print(f"\nQuestion {idx + 1}/{len(df)} [{difficulty}]:")
        print(f"Q: {question}")

        # Get agent's answer with client_id if available
        try:
            if pd.notna(client_id):
                agent_answer = answer(question, client_id=str(int(client_id)))
            else:
                agent_answer = answer(question)
        except Exception as e:
            agent_answer = f"Error: {str(e)}"
            
        print(f"Agent: {agent_answer[:200]}..." if len(agent_answer) > 200 else f"Agent: {agent_answer}")

        # Evaluate the response using LLM-as-a-judge
        eval_result = evaluate_response(question, expected_answer, agent_answer, llm)
        score = eval_result["score"]
        reasoning = eval_result["reasoning"]
        
        total_score += score
        max_score += 5
        scores_by_difficulty[difficulty].append(score)

        print(f"Score: {score}/5")
        print(f"Reasoning: {reasoning}")

        # Store results
        results.append({
            "Question": question,
            "Expected Answer": expected_answer,
            "Agent Answer": agent_answer,
            "Difficulty": difficulty,
            "Score": score,
            "Reasoning": reasoning
        })

        print("-" * 80)

    # Calculate final metrics
    accuracy = (total_score / max_score) * 100 if max_score > 0 else 0
    print("\n" + "=" * 80)
    print("EVALUATION RESULTS")
    print("=" * 80)
    print(f"Total questions: {len(df)}")
    print(f"Total score: {total_score}/{max_score}")
    print(f"Overall accuracy: {accuracy:.2f}%")
    print(f"Average score: {total_score/len(df):.2f}/5")
    
    # Print breakdown by difficulty
    print("\nBreakdown by difficulty:")
    for diff in ["Facile", "Moyen", "Difficile", "Très Difficile"]:
        if scores_by_difficulty[diff]:
            avg = sum(scores_by_difficulty[diff]) / len(scores_by_difficulty[diff])
            print(f"  {diff}: {avg:.2f}/5 ({len(scores_by_difficulty[diff])} questions)")

    # Save results to Excel
    results_df = pd.DataFrame(results)
    results_df.to_excel("evaluation_results.xlsx", index=False)
    print("\nResults saved to: evaluation_results.xlsx")


if __name__ == "__main__":
    run_evaluation()
